apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: statuschecker
  name: marketplace-be-statuschecker
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: statuschecker
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: statuschecker
    spec:
      containers:
      - image: 192.168.110.135:5000/statuschecker:test
        name: statuschecker